version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: FlightPlanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flightplanner:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=
    depends_on:
      - postgres

volumes:
  pgdata:
