version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: flightplanner
      POSTGRES_PASSWORD: flightplanner
      POSTGRES_DB: flightplanner
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=flightplanner;Username=flightplanner;Password=flightplanner"
    depends_on:
      - db
volumes:
  db-data:
