databases:
  - name: flightplanner-db

services:
  - type: web
    name: flightplanner-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: flightplanner-db
          property: connectionString
