services:
  - type: web
    name: flightplanner
    env: docker
    plan: free
    repo: https://github.com/DevArv/FlightPlanner
    branch: production
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      -key: ASPNETCORE_URLS
      value: http://0.0.0.0:80
