databases:
  - name: flightplanner-db

services:
  - type: web
    name: flightplanner
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d12slgmmcj7s73fnsgfg-a;Port=5432;Database=flightplanner_db;Username=flightplanner_db_user;Password=KVTWPiBRZd9zo4bR8pRdLgcgdxu4KvdA
